# Generated by Django 4.2.7 on 2023-11-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.timestamp')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.URLField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('Sage', 'Sage'), ('Other', 'Other')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('integration.timestamp',),
        ),
    ]
