# Generated by Django 5.0.4 on 2024-04-26 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcarditem',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcarditem',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_card_items', to='job_card.jobcard'),
        ),
    ]
