# Generated by Django 5.0.4 on 2024-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0002_jobcarditem_created_jobcarditem_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarditem',
            name='unit_price',
            field=models.IntegerField(default=1),
        ),
    ]
