# Generated by Django 5.0.4 on 2024-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0003_jobcarditem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Minor Service', 'Minor Service'), ('Major Service', 'Major Service'), ('Replacement', 'Replacement'), ('Fitment', 'Fitment')], max_length=255, null=True),
        ),
    ]
