# Generated by Django 5.0.4 on 2024-04-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('SALE', 'SALE'), ('BREAKAGE', 'BREAKAGE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock'),
        ),
    ]
