# Generated by Django 5.0.4 on 2024-04-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='movement_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Flagged', 'Flagged')], default='Pending', max_length=255),
        ),
    ]
