# Generated by Django 5.0.4 on 2024-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_movement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='status_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
