# Generated by Django 5.0.4 on 2024-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_user_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('SALE', 'SALE'), ('USAGE', 'USAGE'), ('BREAKAGE', 'BREAKAGE')], max_length=255),
        ),
    ]
