# Generated by Django 5.0.4 on 2024-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='identifier',
            field=models.IntegerField(default=1),
        ),
    ]
