name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      
      env:
          DJANGO_SECRET_KEY: "c0y7^zo53cwo$0!4(7ife!=%$46wk=6*)g$rgivz41uncm%z@)"
          DEBUG: 1
          MONGO_DB_PSW_SECRET_KEY: ""
          USE_MYSQL: False
          MYSQL_DB_NAME: "DB"
          MYSQL_DB_USER: ""
          MYSQL_DB_PASSWORD: ""
          MYSQL_DB_HOST: ""
          MYSQL_DB_PORT: ""
          SECRET_KEY: ""
          EMAIL_HOST: ""
          EMAIL_PORT: 587
          EMAIL_HOST_USER: ""
          DEFAULT_FROM_EMAIL: ""
          EMAIL_HOST_PASSWORD: ""
          EMAIL_USE_TLS: True
          DEFAULT_RECIPIENT: ""